
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Windows - 10.0.19045 - AMD64
...
